### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kty990** [kty990/dynakit#1]
- [ ] Router tag, route tag: Re-renders page based on route.

- [ ] Add 'redirect' event to cElement

- [ ] Add 'Tween' sub-library

**Comment by kty990** [comment]
Route tag:

```html
<Route dest="../example/html/routeExample.html" text="Example Route">
<!-- HTML to be displayed on route -->
</Route>
```

Router tag:

```html
<Router dest="" onchange="foo()" text="">
<!-- No closing tag -->
```

**Comment by kty990** [comment]
Router tag should prioritize javascript execution whereas Route should prioritize single page redirect

**Comment by kty990** [comment]
# Tween Sub-library

```ts

export class TweenInfo {
    width: string | undefined;
    height: string | undefined;
    color: string | undefined;
    backgroundColor: string | undefined;
    borderWidth: string | undefined;
    borderColor: string | undefined;
    borderRadius: string | undefined;
    left: string | undefined;
    top: string | undefined;
    right: string | undefined;
    bottom: string | undefined;
    transform: string | undefined;
    filter: string | undefined;

    constructor(...args: Array<cArgument>) {
        for (let arg of args) {
            if (arg.name in this) {
                // Use square brackets to set the property dynamically
                this[arg.name] = arg.value;
            }
        }
    }
}

export class Tween {
    constructor(element: HTMLElement, Properties: TweenInfo) {
        for (const prop in Properties) {
            if (Properties.hasOwnProperty(prop)) {
                const propertyValue = Properties[prop];
                // Finish this
            }
        }
    }
}

```
